name: Check Python Version

on:
  push:
    branches:
      - main
    paths:
      - 'python/**'
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'

jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Python version
        run: |
          python --version
        working-directory: ./python
      - name: Uninstall Python
        run: |
          sudo apt-get remove --purge -y python* libpython*
          sudo apt-get autoremove -y
      - name: Check Python version
        run: |
          python --version
        working-directory: ./python
